name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  x_kill_processes:
    name: Kill residual Xcode and Simulator Processes
    run: |
      echo "Terminating all Simulator and Xcode-related processes..."
      killall "Simulator" 2>/dev/null || true
      killall "SimulatorTrampoline" 2>/dev/null || true
      killall "CoreSimulatorService" 2>/dev/null || true
      killall "xcodebuild" 2>/dev/null || true
      killall "swift-frontend" 2>/dev/null || true
      killall "ibtool" 2>/dev/null || true
      killall "Xcode" 2>/dev/null || true
      echo "Process cleanup complete."
    
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26]
        xcode: ['Xcode_26.0']
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3

    - *x_kill_processes

    - name: Build and Test
      run: set -o pipefail && xcodebuild -enableCodeCoverage YES -scheme FioriSwiftUI-Package -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 17,OS=26.0.1' clean build test | xcpretty
      
    - name: Create code coverage report
      run: ./scripts/xccov-to-sonarqube-generic.sh /Users/runner/Library/Developer/Xcode/DerivedData/cloud-sdk-ios-fiori*/Logs/Test/*.xcresult/ > sonarqube-generic-coverage.xml
      
    - name: Store coverage for sonar job
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: sonarqube-generic-coverage.xml

  sonar:
    needs: build
    if: github.event_name == 'push' && github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Get coverage from build job
      uses: actions/download-artifact@v4
      with:
        name: coverage
        
    - name: Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

  build_watch:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26]
        xcode: ['Xcode_26.0']
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3

    - *x_kill_processes

    - name: Run tests on Apple Watch simulator
      run: set -o pipefail && make test_watch

  build_vision:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26]
        xcode: ['Xcode_26.0']
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3

    - *x_kill_processes
      
    - name: Run tests on Vision OS simulator
      run: set -o pipefail && make test_vision
